version: 2.1

commands:
  set_foo_envvar:
    parameters:
      env:
        type: enum
        enum:
          - SANDBOX
          - TEST
    steps:
      - run:
          name: Set FOO env var
          command: |
            echo 'export FOO=<< parameters.env >>' >> $BASH_ENV
  try_cond_on_foo:
    parameters:
      my_env_name:
        type: env_var_name
        default: BAR
    steps:
      - when:
          condition:
            equal: [ "FOO", << parameters.my_env_name >> ]
          steps:
            - run: |
                echo "hello FOO"

jobs:
  cond1:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - set_foo_envvar:
          env: SANDBOX
      - run:
          name: Diagnose
          command: printenv FOO
      - try_cond_on_foo:
          my_env_name: FOO
          

workflows:
  demo:
    jobs:
      - cond1
